steps:
  - name: 'gradle:6.8.3-jdk11'
    entrypoint: gradle
    args: ['test']
  - name: 'gradle:6.8.3-jdk11'
    entrypoint: gradle
    args: ['assemble']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/springboot-container-test', '--build-arg=JAR_FILE=build/libs/*.jar', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/springboot-container-test' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pagu-study-community'
      - '--image'
      - 'gcr.io/$PROJECT_ID/springboot-container-test'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'