steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['install']
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/pagu-community/springboot-container-test', '--build-arg=JAR_FILE=build/libs/build-artifact', '.' ]
images: [ 'gcr.io/project-id/image-name' ]