steps:
  - name: 'gradle:6.8.3-jdk11'
    entrypoint: gradle
    args: ['test']
  - name: 'gradle:6.8.3-jdk11'
    entrypoint: gradle
    args: ['assemble']
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/phrasal-period-309310/springboot-container-test', '--build-arg=JAR_FILE=build/libs/*.jar', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/phrasal-period-309310/spring-boot-container-test' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrunservice'
      - '--image'
      - 'gcr.io/phrasal-period-309310/springboot-container-test'
      - '--allow-unauthenticated'